# Generated by Django 2.0.1 on 2018-01-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='country',
            name='flag_image',
            field=models.ImageField(null=True, upload_to='flags'),
        ),
    ]
