# Generated by Django 2.0.1 on 2018-01-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180126_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='flags'),
        ),
    ]
